# Copyright (C) Eta Scale AB. Licensed under the Eta Scale Open Source License. See the LICENSE file for details.

LEVEL=../..

include $(LEVEL)/common/Defines.common.mk
include ./Defines.common.mk
include $(LEVEL)/common/Makefile.common


