# Copyright (C) Eta Scale AB. Licensed under the Eta Scale Open Source License. See the LICENSE file for details.

######
# Setting the targets to build
# 

# Targets to build
#INDIR_COUNT=1 2 4 8
#GRAN_COUNT=2 4 8
INDIR_COUNT=25
GRAN_COUNT=1

ORIGINAL_SUFFIX=original
OPT_SUFFIX=opt
PASS_SUFFIX=pass
DAE_SUFFIX=dae
ENABLE_STATS=no
#CAE_SUFFIX=cae
#DAE_TYPE=dae

# Targets
#ORIGINAL_TARGETS=$(BENCHMARK).$(ORIGINAL_SUFFIX)
#ORIGINAL_TARGETS=$(BENCHMARK).$(ORIGINAL_SUFFIX).V0 $(BENCHMARK).$(ORIGINAL_SUFFIX).V1 $(BENCHMARK).$(ORIGINAL_SUFFIX).V2 $(BENCHMARK).$(ORIGINAL_SUFFIX).V3 $(BENCHMARK).$(ORIGINAL_SUFFIX).V4
 
ORIGINAL_TARGETS+=$(BENCHMARK).$(ORIGINAL_SUFFIX).V3
#DAE_TARGETS=$(foreach type, $(DAE_TYPE), \
		 $(foreach indir, $(INDIR_COUNT), \
			$(foreach gran, $(GRAN_COUNT), \
				$(BENCHMARK).gran$(gran).indir$(indir).$(type))))

#CAE_TARGETS=$(foreach indir, $(INDIR_COUNT), $(BENCHMARK).gran$(indir).$(CAE_SUFFIX))

#ALLTARGETS=$(DAE_TARGETS) $(CAE_TARGETS) $(ORIGINAL_TARGETS) 
#ALLTARGETS=$(DAE_TARGETS) $(ORIGINAL_TARGETS) 
ALLTARGETS=$(ORIGINAL_TARGETS) 

# Output directory
BINDIR=../bin

# TARGETS
TARGETS=$(addprefix $(BINDIR)/, $(ALLTARGETS))




