# Copyright (C) Eta Scale AB. Licensed under the Eta Scale Open Source License. See the LICENSE file for details.

######
# Setting the environment variables 
#

COMPILER_LIB=$(HOME)/llvm/daedal/compiler/build/projects-build/lib
LLVM_BIN=$(HOME)/llvm/daedal/compiler/build/llvm-build/bin/
PASS_DIR=$(HOME)/llvm/daedal/compiler/build/projects-build/lib
PASS_NAME=libTM_pass.so
PASS_FLAGS := -tm_pass
